GRANT EXECUTE ON pkg_passenger_mgmt TO TRAIN_APP;
GRANT EXECUTE ON pkg_train_mgmt     TO TRAIN_APP;
GRANT EXECUTE ON pkg_reservation    TO TRAIN_APP;

GRANT SELECT ON CRS_PASSENGER      TO TRAIN_APP;
GRANT SELECT ON CRS_RESERVATION    TO TRAIN_APP;
GRANT SELECT ON CRS_TRAIN_INFO     TO TRAIN_APP;
GRANT SELECT ON CRS_DAY_SCHEDULE   TO TRAIN_APP;
GRANT SELECT ON CRS_TRAIN_SCHEDULE TO TRAIN_APP;



SET SERVEROUTPUT ON;
